version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./api:/var/www/api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            -  "8080:80"
        depends_on:
            - php_fpm
        networks:
            - monitoring

    php_fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./api:/var/www/api
        networks:
            - monitoring

    ui:
        build:
            context: .
            dockerfile: docker/ui/Dockerfile
        command: "npm start"
        networks:
            - monitoring
        volumes:
            - ${PWD}/ui:/var/www/ui:delegated
        ports:
            - "3000:3000"

volumes:
    nodemodules: {}

networks:
    monitoring:
        driver: bridge
