version: "3.9"

services:
    calculator_nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            -   "8080:80"
    calculator_fpm:
        build:
            context: .
            dockerfile: .docker/php/dockerfile
        volumes:
            - ./:/var/www/html
