version: "3.9"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./api:/var/www/api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            -   "8080:80"
        depends_on:
            - php_fpm
            - ui
        networks:
            - monitoring

    php_fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./api:/var/www/api
        networks:
            - monitoring

    ui:
        build:
            dockerfile: ./docker/ui/Dockerfile
        command: "npm start"
        networks:
            - monitoring
        volumes:
            - ${PWD}/ui:/var/www/ui
        ports:
            - "3000:3000"

networks:
    monitoring:
        driver: bridge
